namespace: coder

user:
  name: imran
  pvcSize: 50Gi
  host: imran.dev.scalebase.io
  env:
    - name: GIT_USER_NAME
      value: "Imran Ali"
    - name: GIT_USER_EMAIL
      value: "imran@scalebase.io"

image:
  repository: registry.digitalocean.com/resourceloop/coder
  tag: devlaptop-v1.6.2-browser-stealth
  pullPolicy: Always
  pullSecretName: regcred

ingress:
  className: nginx
  auth:
    type: oauth2  # Changed from 'basic' to 'oauth2'
    secretName: api-basic-auth  # Keep for fallback
  tls:
    enabled: true
    secretName: imran-dev-scalebase-io-tls
    clusterIssuer: letsencrypt-production

# OAuth2 configuration 
oauth2:
  # GitHub user authorization - comma-separated list of GitHub usernames
  githubUsers: "imran31415"  # Authorized GitHub usernames
  # Secrets are provided separately in secrets/imran/oauth2.yaml
  cookieSecret: "PLACEHOLDER-OVERRIDE-WITH-SECRETS-FILE"
  clientId: "PLACEHOLDER-OVERRIDE-WITH-SECRETS-FILE"
  clientSecret: "PLACEHOLDER-OVERRIDE-WITH-SECRETS-FILE"

resources:
  requests:
    cpu: "2"
    memory: 3Gi
  limits:
    cpu: "3"
    memory: 5Gi

build:
  mode: buildkit
  kanikoImage: gcr.io/kaniko-project/executor:latest
  pushSecretName: regcred
  defaultDestinationRepo: registry.digitalocean.com/resourceloop/coder

ssh:
  enabled: false
  port: 22