namespace: coder

image:
  repository: registry.digitalocean.com/resourceloop/coder
  tag: devlaptop-v1.4.0
  pullPolicy: IfNotPresent
  pullSecretName: regcred

ingress:
  className: nginx
  auth:
    type: basic
    secretName: api-basic-auth
  tls:
    enabled: true
    secretName: imran-dev-scalebase-io-tls
    clusterIssuer: letsencrypt-production

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 4Gi

build:
  mode: buildkit
  kanikoImage: gcr.io/kaniko-project/executor:latest
  pushSecretName: regcred
  defaultDestinationRepo: registry.digitalocean.com/resourceloop/coder

ssh:
  enabled: false
  port: 22

users:
  - name: imran
    pvcSize: 50Gi
    host: imran.dev.scalebase.io
    env:
      - name: GIT_USER_NAME
        value: "Imran Ali"
      - name: GIT_USER_EMAIL
        value: "imran@scalebase.io"