namespace: coder

image:
  # Build & push this image first (see devlaptop/Dockerfile)
  repository: registry.digitalocean.com/resourceloop/coder
  tag: devlaptop-v0.1.0
  pullPolicy: IfNotPresent

ingress:
  className: nginx
  tls:
    enabled: false         # set to true when your TLS secret is ready
    secretName: ""         # e.g., dev-scalebase-io-tls
  auth:
    type: basic            # protects IDE with nginx basic-auth
    secretName: api-basic-auth   # create in the 'coder' namespace

domain: dev.scalebase.io  # per-user hosts like imran.dev.scalebase.io

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "4"
    memory: "8Gi"

build:
  mode: kaniko
  kanikoImage: gcr.io/kaniko-project/executor:latest
  pushSecretName: regcred
  defaultDestinationRepo: registry.digitalocean.com/resourceloop/coder

ssh:
  enabled: false
  port: 22

users:
  - name: imran
    pvcSize: 50Gi
    host: imran.dev.scalebase.io
    env: []
  # - name: alice
  #   pvcSize: 40Gi
  #   host: alice.dev.scalebase.io
  #   env: []
