{{- range .Values.users }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ws-{{ .name }}
  namespace: {{ $.Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ws-{{ .name }}-builder
  namespace: {{ $.Values.namespace }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create","get","list","watch","delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ws-{{ .name }}-builder-binding
  namespace: {{ $.Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: ws-{{ .name }}
roleRef:
  kind: Role
  name: ws-{{ .name }}-builder
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
