namespace: coder

user:
  name: gerard
  pvcSize: 50Gi
  host: gerard.dev.scalebase.io
  env:
    - name: GIT_USER_NAME
      value: "Gerard Developer"
    - name: GIT_USER_EMAIL
      value: "gerard@scalebase.io"

image:
  repository: registry.digitalocean.com/resourceloop/coder
  tag: devlaptop-v1.5.0
  pullPolicy: Always
  pullSecretName: regcred

ingress:
  className: nginx
  auth:
    type: basic
    secretName: gerard-basic-auth
  tls:
    enabled: true
    secretName: gerard-dev-scalebase-io-tls
    clusterIssuer: letsencrypt-production

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 4Gi

build:
  mode: buildkit
  kanikoImage: gcr.io/kaniko-project/executor:latest
  pushSecretName: regcred
  defaultDestinationRepo: registry.digitalocean.com/resourceloop/coder

ssh:
  enabled: false
  port: 22