apiVersion: v1
kind: ServiceAccount
metadata:
  name: ws-{{ .Values.user.name }}
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ws-{{ .Values.user.name }}-build
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ws-{{ .Values.user.name }}-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ws-{{ .Values.user.name }}-build
subjects:
- kind: ServiceAccount
  name: ws-{{ .Values.user.name }}
  namespace: {{ .Values.namespace }}