{{- if .Values.ssh.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ssh-authorized-keys-{{ .Values.user.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  authorized_keys: |
{{ .Values.ssh.authorizedKeys | indent 4 }}
{{- end }}
