#!/usr/bin/env bash
# scripts/setup-controller-provisioning.sh — one-time setup for the controller's
# self-service provisioning feature (the "New workspace" button).
#
# Usage:
#   scripts/setup-controller-provisioning.sh \
#       --domain dev.example.io \
#       --gitops-repo github.com/<you>/kube-coder-users.git \
#       [--github-org <org>] \
#       [--chart-repo https://github.com/<you>/kube-coder.git] \
#       [--git-token <token>]
#
# What it does (idempotent — existing secrets are preserved):
#   1. Generates a random state-secret (HMAC key for the manifest flow).
#   2. Writes users-private/_controller/secrets/provision.yaml (gitignored) —
#      a Helm values overlay carrying provision.gitToken + provision.stateSecret.
#   3. Prints the `provision:` block to merge into
#      users-private/_controller/values.yaml, and the remaining manual steps
#      (create the private GitOps repo + a push token).
#
# Provisioning stays OFF until you set provision.enabled=true in that values
# file and redeploy: `make ship-controller-config`.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CTRL_DIR="$ROOT/users-private/_controller"
SECRET_OUT="$CTRL_DIR/secrets/provision.yaml"

DOMAIN=""
GITOPS_REPO=""
GITHUB_ORG=""
CHART_REPO=""
GIT_TOKEN=""

while [ $# -gt 0 ]; do
  case "$1" in
    --domain) DOMAIN="$2"; shift 2 ;;
    --gitops-repo) GITOPS_REPO="$2"; shift 2 ;;
    --github-org) GITHUB_ORG="$2"; shift 2 ;;
    --chart-repo) CHART_REPO="$2"; shift 2 ;;
    --git-token) GIT_TOKEN="$2"; shift 2 ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "ERROR: unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [ -z "$DOMAIN" ] || [ -z "$GITOPS_REPO" ]; then
  echo "ERROR: --domain and --gitops-repo are required. See --help." >&2
  exit 2
fi

mkdir -p "$CTRL_DIR/secrets"

# HMAC key signing the manifest-flow state param. 48 url-safe-ish chars of
# entropy; only the controller ever reads it, so any opaque random string works.
STATE_SECRET=$(openssl rand -base64 64 | tr -d '\n=+/' | head -c 48)

if [ -f "$SECRET_OUT" ]; then
  echo "• $SECRET_OUT already exists — leaving it untouched."
  echo "  (delete it and re-run to regenerate the state-secret.)"
else
  cat > "$SECRET_OUT" <<EOF
# Provisioning credentials for workspace-controller — generated by
# scripts/setup-controller-provisioning.sh. GITIGNORED. Never commit.
#
# git-token: paste a token that can PUSH to your GitOps repo and READ the
# GitHub API. A fine-grained PAT scoped to just that one repo (Contents: RW)
# is the simplest option; a GitHub App installation token also works.
provision:
  gitToken: "${GIT_TOKEN:-PASTE-GIT-TOKEN-HERE}"
  # Random HMAC key — no need to change this.
  stateSecret: "${STATE_SECRET}"
EOF
  echo "• wrote $SECRET_OUT (state-secret generated)."
  if [ -z "$GIT_TOKEN" ]; then
    echo "  → edit it and replace PASTE-GIT-TOKEN-HERE with your push token."
  fi
fi

CHART_LINE=""
if [ -n "$CHART_REPO" ]; then
  CHART_LINE="  chart:
    repo: ${CHART_REPO}
    ref: main"
fi
ORG_LINE=""
if [ -n "$GITHUB_ORG" ]; then
  ORG_LINE="  githubOrg: ${GITHUB_ORG}"
fi

cat <<EOF

──────────────────────────────────────────────────────────────────────────────
Next steps
──────────────────────────────────────────────────────────────────────────────

1. Create a PRIVATE GitOps repo for generated workspace config, with an initial
   commit on its default branch (an empty repo can't be cloned):

     gh repo create <you>/$(basename "$GITOPS_REPO" .git) --private \\
       --add-readme --clone=false

2. Create a push token for that repo (Contents: read+write) and put it in the
   gitToken field of:
     $SECRET_OUT

3. Add this block to users-private/_controller/values.yaml (merge into any
   existing keys), then flip enabled to true:

provision:
  enabled: true
  workspaceDomain: ${DOMAIN}
  gitops:
    repo: ${GITOPS_REPO}
    branch: main
${CHART_LINE}
${ORG_LINE}

   (Requires wildcard DNS *.${DOMAIN} pointing at your ingress.)

4. Deploy:  make ship-controller-config

5. Open https://<controller-host> → "New workspace".

Full guide: docs/PROVISIONING.md
EOF
